from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Dict, Optional
from uuid import UUID, uuid4

from ...schemas.meal import MealItem, MealPlanCreateRequest, MealPlanResponse, ShoppingListItem


@dataclass
class MealPlanRecord:
    id: UUID
    user_email: str
    week_start: date
    meals: list[MealItem] = field(default_factory=list)
    shopping_list: list[ShoppingListItem] = field(default_factory=list)
    status: str = "draft"

    def to_response(self) -> MealPlanResponse:
        return MealPlanResponse(
            id=self.id,
            user_email=self.user_email,
            week_start=self.week_start,
            meals=self.meals,
            shopping_list=self.shopping_list,
            status=self.status,
        )


class MealPlanService:
    """Simple in-memory service representing the design's domain service layer."""

    def __init__(self, storage: Dict[UUID, MealPlanRecord]):
        self._storage = storage
        self._last_created_id: UUID | None = None

    @classmethod
    def create_in_memory(cls) -> "MealPlanService":
        return cls(storage={})

    def create_meal_plan(self, payload: MealPlanCreateRequest) -> MealPlanResponse:
        plan_id = uuid4()
        # Minimal deterministic content for demo purposes
        meals = [
            MealItem(
                day_of_week=day,
                meal_type="dinner",
                recipe_title=f"{payload.culture_id}-inspired {day} special",
                instructions="Enjoy responsibly. Generated by stub workflow.",
            )
            for day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
        ]
        shopping_list = [
            ShoppingListItem(name="Chickpeas", quantity="2 cans"),
            ShoppingListItem(name="Spinach", quantity="500g"),
        ]
        record = MealPlanRecord(
            id=plan_id,
            user_email=payload.email,
            week_start=date.today(),
            meals=meals,
            shopping_list=shopping_list,
            status="ready",
        )
        self._storage[plan_id] = record
        self._last_created_id = plan_id
        return record.to_response()

    def get_meal_plan(self, plan_id: str) -> Optional[MealPlanResponse]:
        try:
            uid = UUID(plan_id)
        except ValueError:
            return None
        record = self._storage.get(uid)
        return record.to_response() if record else None

    def get_latest(self) -> Optional[MealPlanResponse]:
        if not self._last_created_id:
            return None
        record = self._storage.get(self._last_created_id)
        return record.to_response() if record else None
