FROM node:20-bullseye-slim AS build
WORKDIR /app
ENV npm_config_platform=linux \
    npm_config_arch=arm64
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install
COPY frontend ./frontend
WORKDIR /app/frontend
RUN npm run build

FROM nginx:1.25-alpine
COPY --from=build /app/frontend/dist /usr/share/nginx/html
COPY infra/docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
